# This file should be an exact copy of the original in wp-data-model:
# https://github.com/ideasonpurpose/wp-data-model/blob/master/example/.github/workflows/publish-to-aws.yml

name: Push Update to AWS

on:
  push:
    tags: ["v*"]

  workflow_dispatch:

env:
  S3_URI: s3://ideasonpurpose-wp-updates
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, bundle and deploy to AWS

    steps:
      - uses: actions/checkout@v2

      - name: Set up REPO and TAG environment vars
        run: |
          echo  "REPO=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo  "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: No tag, use SHA for output name
        if: ${{ ! startsWith(github.ref, 'refs/tags') }}
        run: |
          echo "TAG=${GITHUB_SHA:0:6}" >> $GITHUB_ENV

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create Zip Archive
        run: |
          cd ../
          rm -rf ${REPO}.zip
          zip -r ${REPO}.zip ${REPO} -i ${REPO}/main.php ${REPO}/lib/\* ${REPO}/vendor/\* ${REPO}/readme.txt

      - name: Render README and CHANGELOG HTML
        run: |
          npx marked -o assets/about.html README.md
          npx marked -o assets/changelog.html CHANGELOG.md

      # - name: Generate metadata.json file
      #   run: |
      #     curl -s http://api.wordpress.org/core/stable-check/1.0/ | jq 'to_entries[] | {tested: select(.value == "latest").key}' > ${{ runner.temp }}/tested.json
      #     cat package.json| jq '{homepage: .homepage}' > ${{ runner.temp }}/homepage.json
      #     jq -s '.[0] * .[1]'  ${{ runner.temp }}/homepage.json ${{ runner.temp }}/tested.json > assets/metadata.json

      - name: Send artifacts to S3
        run: |
          aws s3 sync assets $S3_URI/${REPO}
          aws s3 cp ../${REPO}.zip $S3_URI/${REPO}.zip
          aws s3 cp $S3_URI/${REPO}.zip $S3_URI/${REPO}_${TAG}.zip
