name: Build and Publish

on:
  push:
    branches: ["*"]
    tags: ["v*"]

env:
  S3_URI: s3://ideasonpurpose-wp-updates
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-2

jobs:
  build:
    name: Build, bundle and deploy to AWS
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-22.04

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      - name: Set up REPO and TAG environment vars
        run: |
          echo "REPO=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA:0:6}" >> $GITHUB_ENV

      - name: This run was triggered by a version tag, reset the $TAG variable to the tag name
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo  "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create Zip Archive
        run: |
          cd ../
          rm -rf ${REPO}.zip
          zip -r ${REPO}.zip ${REPO} -i ${REPO}/main.php ${REPO}/lib/\* ${REPO}/vendor/\*

      - name: Render README to HTML
        run: |
          npx marked -o assets/about.html README.md
          npx marked -o assets/changelog.html CHANGELOG.md

      - name: Store Artifact
        # https://github.com/marketplace/actions/upload-a-build-artifact#v4---whats-new
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO }}
          path: |
            main.php
            lib/*
            vendor/*
          retention-days: 3

      - name: Create GitHub release
        if: ${{ contains(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${TAG} ../${REPO}.zip

      - name: Send artifacts to S3
        if: ${{ contains(github.ref, 'refs/tags/') && env.AWS_ACCESS_KEY_ID }}
        run: |
          aws s3 sync assets $S3_URI/${REPO}
          aws s3 cp ../${REPO}.zip ${S3_URI}/${REPO}/${REPO}_${TAG}.zip
