version: "3.7"

services:
  composer:
    image: composer
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  wp-tested:
    image: realguess/jq:1.4
    volumes:
      - ./:/app
    command: |
      sh -c "cat /app/package.json | jq '{homepage: .homepage}' > /tmp/homepage.json &&
             wget -q -O- http://api.wordpress.org/core/stable-check/1.0 | jq 'to_entries[] | {tested: select(.value == \"latest\").key}' > /tmp/tested.json &&
             jq -s '.[0] * .[1]'  /tmp/homepage.json /tmp/tested.json > /app/assets/metadata.json"
