version: "3.7"

services:
  # This is a little silly, but the advantage of using docker-compose
  # is that all relatives paths are automatically cross-platform.
  # Bare docker commands would need to know the platform and switch
  # from `${PWD}` on Mac/Linux and %CD% on Windows.
  composer:
    image: composer
    volumes:
      - ./:/app
    command: install
