services:
  # https://hub.docker.com/_/composer
  composer:
    image: composer:2
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  # https://www.github.com/ideasonpurpose/docker-phpunit-watch
  test:
    # image: ideasonpurpose/phpunit-watch:dev
    image: ideasonpurpose/phpunit-watch:0.1.5
    volumes:
      - ./:/app

  # https://hub.docker.com/r/amazon/aws-cli
  aws:
    image: amazon/aws-cli:2.2.46
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
    volumes:
      - ./aws/:/usr/src/
