services:
  # Utility service for running composer, provides a local volume for storing access tokens
  # https://hub.docker.com/_/composer
  composer:
    image: composer:2.5
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  # https://hub.docker.com/r/ideasonpurpose/phpunit-watch
  test:
    image: ideasonpurpose/phpunit-watch:1.3.0
    volumes:
      - ./:/app

  # https://hub.docker.com/r/amazon/aws-cli
  aws:
    image: amazon/aws-cli:2.13
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
    volumes:
      - ./aws/:/usr/src/
