services:
  composer:
    image: composer:2.1.9
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  test:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: []
    command: vendor/bin/phpunit

  aws:
    image: amazon/aws-cli:2.2.46
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
    volumes:
      - ./aws/:/usr/src/
